FROM nginx:alpine

RUN rm -f /usr/share/nginx/html/*

COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN sed -i -e "s/__BUILD_DATE__/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/g" /usr/share/nginx/html/index.html

EXPOSE 80